### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by braco** [gaving/searchkit-geomap#3]

**Comment by gaving** [comment]
Hi - 

I'd say it's looking that way, I attempted knocking it into shape a few weeks ago for React 16 + recent searchkit + recent react-map-gl but gave up due to a (suspected) incompatibility in the otherwise undocumented demo `/crimes` api.

More details here:-

https://gitter.im/searchkit/searchkit?at=5a211b1271ad3f8736514ae4

> I appreciate the `/crimes` API isn't documented or supported, but I presume the `location` mapping hasn't been updated to be a `geo_point` type for the newer ES version? Seem to be getting this back: https://gist.github.com/gaving/e5efcd55ad4c6e637718097ec2206441 (already had to update `filtered` to a bool query for ES5+). I'm basically trying to batter https://github.com/gaving/searchkit-geomap into 2017 but getting stuck on this... 

I've pushed the changes where I got to another branch here:- https://github.com/gaving/searchkit-geomap/commit/a90ff77c42a795eaf5551f580cfbd1ba89dc196d

I'll maybe look again one of these days but really needed geo_point types for the next version of Elastic Search from memory.

**Comment by juliendangers** [comment]
Got it to work fine with Elasticsearch 6 and latest version of searchkit !

Had to replace filtered query with 
```
{
    bool: {
        filter: {
            geo_bounding_box: {
                location: this.area
            }
        }
    }
}
```

**Comment by gaving** [comment]
Julien -

Cool! Happy to take a PR!

Cheers,
Gavin

**Comment by gaving** [comment]
Closing this, merged @juliendangers changes and things appear to be working for later versions.

Will look at merging the `next` branch in at some point.

**Comment by juliendangers** [comment]
:warning: my PR was on your own next branch, not on master

**Comment by gaving** [comment]
@juliendangers Ah yeah I noticed after I wrote that reply, appears it just needs some README updates to reference the new React stuff and I think it should be good to go.

**Comment by gaving** [comment]
@juliendangers 

Just having a look at merging `next`, but seems I'm getting the same error from what I remember from the crimes API:- 

> curl 'http://demo.searchkit.co/api/crimes/_search' -H 'Pragma: no-cache' -H 'Origin: http://localhost:3000' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US,en;q=0.9' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36' -H 'Content-Type: application/json;charset=UTF-8' -H 'Accept: application/json, text/plain, */*' -H 'Cache-Control: no-cache' -H 'Referer: http://localhost:3000/?q=theft' -H 'Connection: keep-alive' --data-binary '{"query":{"bool":{"must":[{"simple_query_string":{"query":"theft","fields":["_all"]}},{"bool":{"filter":{"geo_bounding_box":{"location":{"top_left":{"lat":54.39263858926111,"lon":-4.0022979945921495},"bottom_right":{"lat":52.021516594919255,"lon":1.2780468883425156}}}}}}]}},"aggs":{"geo":{"filter":{"match_all":{}},"aggs":{"areas":{"geohash_grid":{"field":"location"},"aggs":{"cell":{"geo_bounds":{"field":"location"}}}},"bounds":{"geo_bounds":{"field":"location"}}}}},"size":20}' --compressed

Response:-

```
{
  "error": {
    "root_cause": [
      {
        "type": "query_shard_exception",
        "reason": "failed to find geo_point field [location]",
        "index_uuid": "jh7WcC8sSn-w6n6pEaS27A",
        "index": "crimes"
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "crimes",
        "node": "rHYVvIt0Ry-jp1Ih5zGDew",
        "reason": {
          "type": "query_shard_exception",
          "reason": "failed to find geo_point field [location]",
          "index_uuid": "jh7WcC8sSn-w6n6pEaS27A",
          "index": "crimes"
        }
      }
    ],
    "caused_by": {
      "type": "query_shard_exception",
      "reason": "failed to find geo_point field [location]",
      "index_uuid": "jh7WcC8sSn-w6n6pEaS27A",      "index": "crimes"
    }
  },
  "status": 400
}
```

If you get a second could you pull the latest changes from `next` and see if you can re-create this? Should be using your replaced filter query.

**Comment by juliendangers** [comment]
I used my own Elasticsearch indices to test it. Crimes API doesn't seem to be up to date...
Are you that tied up with the crimes API?

**Comment by gaving** [comment]
@juliendangers 

I see, that's my misunderstanding then as I thought this was based off the hosted searchkit API at demo.searchkit.co so my initial suspicions were correct that it is too old. 

But nah I'm not overly precious about it, just was convenient for the demo.

I'll see how to proceed merging the changes without a working demo...

**Comment by juliendangers** [comment]
Hmm, we could start an Elasticsearch docker container populated with up to date data for the demo

**Comment by gaving** [comment]
Yeah, I guess it depends how important the demo is + the hosting and hassle of all that. Either that or the install instructions specifically document launching a docker container and populating some example bundled json files.

I mean ideally the searchkit guys would just update their API, but I've already tried asking in the gitter channel to silence! 😆
